# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
}

provider "aws" {
  access_key = "test"
  secret_key = "test"
  region     = "us-east-1"

  skip_credentials_validation = true
  skip_region_validation      = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway     = "http://localhost.localstack.cloud:4566"
    apigatewayv2   = "http://localhost.localstack.cloud:4566"
    cloudformation = "http://localhost.localstack.cloud:4566"
    cloudwatch     = "http://localhost.localstack.cloud:4566"
    dynamodb       = "http://localhost.localstack.cloud:4566"
    ec2            = "http://localhost.localstack.cloud:4566"
    es             = "http://localhost.localstack.cloud:4566"
    elasticache    = "http://localhost.localstack.cloud:4566"
    firehose       = "http://localhost.localstack.cloud:4566"
    iam            = "http://localhost.localstack.cloud:4566"
    kinesis        = "http://localhost.localstack.cloud:4566"
    lambda         = "http://localhost.localstack.cloud:4566"
    rds            = "http://localhost.localstack.cloud:4566"
    redshift       = "http://localhost.localstack.cloud:4566"
    route53        = "http://localhost.localstack.cloud:4566"
    s3             = "http://s3.localhost.localstack.cloud:4566"
    secretsmanager = "http://localhost.localstack.cloud:4566"
    ses            = "http://localhost.localstack.cloud:4566"
    sns            = "http://localhost.localstack.cloud:4566"
    sqs            = "http://localhost.localstack.cloud:4566"
    ssm            = "http://localhost.localstack.cloud:4566"
    stepfunctions  = "http://localhost.localstack.cloud:4566"
    sts            = "http://localhost.localstack.cloud:4566"
  }
}
